### ISSUE TITLE
Generic type not dynamically generated in generated class

### ISSUE THREAD

**Issue by ersin-ertan** [tom91136/Akatsuki#6]
Should the generic class type T in the BundleRetainer class be of the same type in MyBean class of Typ?
If not, there could be a type naming clash if I had used T in MyBean and the generated T did not check to see if its name collided with the one in MyBean. 

```java
public class MyBean<Typ extends String> extends RootBean{
	@Retained public Typ     retainedGeneric;
}

public class MyBean$$BundleRetainer<T extends MyBean> extends RootBean$$BundleRetainer<T> {
  public void save(final T source, final Bundle bundle) {
    super.save(source, bundle);
    bundle.putString("retainedGeneric", source.retainedGeneric);
    bundle.putBundle("model", com.sora.util.akatsuki.Akatsuki.serialize(source.model));
  }

  public void restore(final T source, final Bundle bundle) {
    super.restore(source, bundle);
    source.retainedGeneric = (Typ)bundle.getString("retainedGeneric");
    source.model = com.sora.util.akatsuki.Akatsuki.deserialize(source.model, bundle.getBundle("model"));
  }
}
```

**Comment by tom91136** [comment]
I found the cause(The [test](https://github.com/tom91136/Akatsuki/blob/master/akatsuki-compiler/src/test/java/com/sora/util/akatsuki/compiler/SupportedTypeTest.java#L219-L227) passed because it was relying on the fact that `Bundle.getParcelable` has a generic factory).
Working on a fix.

**Comment by tom91136** [comment]
Please upgrade to 0.0.3 as this is a serious bug that might let cast errors go undetected at compile-time
